name = "Mayhem Project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "bpxx1o8kngmf86ei0h2mefay"
name = "Polish"

  [[processes.tasks]]
  id = "ciy0zvo8tsdh5c3wxgetc8e8"
  title = "Orientation not correctly staying put"
  description = "<p>When we release the joystick, orientation often move not correctly</p>"
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "mtzrqgnxdpr1eabjwns6dv4v"
  title = "PlayerHealthManager"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "g0lyyi078zasy8xiig2y6aff"
  title = "Enemy AI"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "bpumvpe1dev3hdun14mukixh"
  title = "Basic LD Block out"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "npqhevj3r6xe3zs1sovf1e0k"
  title = "GDD"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "geqogapazqh60v5sa504u92t"
name = "Documentation"

  [[processes.tasks]]
  id = "yexbn0fivfk36t1bjabstv6x"
  title = "Spawner factory"
  description = "<p>Factory</p><p><code>public class EnemyFactory</code></p><p><code>{</code></p><p><code>    public static Enemy CreateEnemy(string enemyType, Vector3 position)</code></p><p><code>    {</code></p><p><code>        GameObject enemyObject = null;</code></p><p><code>        switch (enemyType.ToLower())</code></p><p><code>        {</code></p><p><code>            case \"police\":</code></p><p><code>                enemyObject = GameObject.Instantiate(Resources.Load(\"PolicePrefab\")) as GameObject;</code></p><p><code>                break;</code></p><p><code>            case \"tank\":</code></p><p><code>                enemyObject = GameObject.Instantiate(Resources.Load(\"TankPrefab\")) as GameObject;</code></p><p><code>                break;</code></p><p><code>            case \"helicopter\":</code></p><p><code>                enemyObject = GameObject.Instantiate(Resources.Load(\"HelicopterPrefab\")) as GameObject;</code></p><p><code>                break;</code></p><p><code>            default:</code></p><p><code>                throw new ArgumentException(\"Invalid enemy type\");</code></p><p><code>        }</code></p><p><code>        if (enemyObject != null)</code></p><p><code>        {</code></p><p><code>            enemyObject.transform.position = position;</code></p><p><code>            Enemy enemy = enemyObject.GetComponent&lt;Enemy&gt;();</code></p><p><code>            enemy.Initialize();</code></p><p><code>            return enemy;</code></p><p><code>        }</code></p><p><code>        return null;</code></p><p><code>    }</code></p><p><code>}</code></p><p>Appel factory</p><p><code>public class LevelManager : MonoBehaviour</code></p><p><code>{</code></p><p><code>    void Start()</code></p><p><code>    {</code></p><p><code>        // Exemples d'instanciation</code></p><p><code>        for (int i = 0; i &lt; 150; i++)</code></p><p><code>        {</code></p><p><code>            EnemyFactory.CreateEnemy(\"police\", GetRandomPosition());</code></p><p><code>        }</code></p><p><code>        for (int i = 0; i &lt; 40; i++)</code></p><p><code>        {</code></p><p><code>            EnemyFactory.CreateEnemy(\"tank\", GetRandomPosition());</code></p><p><code>        }</code></p><p><code>        for (int i = 0; i &lt; 10; i++)</code></p><p><code>        {</code></p><p><code>            EnemyFactory.CreateEnemy(\"helicopter\", GetRandomPosition());</code></p><p><code>        }</code></p><p><code>    }</code></p><p><code>    private Vector3 GetRandomPosition()</code></p><p><code>    {</code></p><p><code>        // Retourne une position aléatoire dans le niveau</code></p><p><code>        return new Vector3(Random.Range(-10, 10), 0, Random.Range(-10, 10));</code></p><p><code>    }</code></p><p><code>}</code></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "pqxxft9395byht97q8f38amo"
  title = "Basic first enemy"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "h7c32lifdogze0o7fcftj73z"
  title = "Basic UI"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "px1abd2d3c29hlrlmws9fojx"
  title = "Zone aiming"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "vuhb2vd31xtewfb5g6rctpds"
  title = "Shoot"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "uh1mquvbft74mdgjg09oq5my"
  title = "Aim"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "kbpcekvjkjq4b14ofkx1xeht"
  title = "Movement"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
